name: igraph &ndash; the network analysis package
destination: docs
future: false
highlighter: pygments
include: [ .htaccess, .htpasswd, _static, _sources, _images, .nojekyll ]
exclude: [ Makefile ]
markdown: redcarpet
redcarpet:
  extensions: [ "autolink" ]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
